[package]
name = "prepper"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
clap = { version = "4.5.21", features = ["derive", "cargo"] }
pg-connection-string = "0.0.2"
pg_replicate = { git = "https://github.com/passcod/pg_replicate", branch = "main" }
serde = { version = "1.0.209", features = ["derive"] }
serde_avro_fast = "2.0.0"
serde_json = "1.0.127"
subtle-encoding = "0.5.1"
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = ["full"] }
tokio-postgres = { git = "https://github.com/MaterializeInc/rust-postgres", default-features = false, rev = "02336bebb28507665184c21566e5d1dc8de1dd7d" }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
