event = {
    0: uint, ; schema version; should be 1
    1: table,
    2: device,
    3: snapshot,
}

buuid = #6.37(bstr)

; tables in Tamanu either have a string id or a uuid
tamanuid = #6.26980(tstr / buuid) ; 0x6964 = 'i' 'd'

; row data translated from the postgres representation
rowdata = #6.28775({ * tstr => any }) ; 0x7067 = pg

table = {
    1: int,  ; oid
    2: tstr, ; schema
    3: tstr, ; name
}

; this is a tag 1001 etime profile with seconds and nanoseconds only
ts = #6.1001(ts-etime)
ts-etime = {
    1: int,   ; seconds since the epoch
    -9: uint, ; nanoseconds fraction
}

device = {
    1: buuid, ; uuid
    2: ts,    ; timestamp of the record as obtained from the device
}

snapshot = {
    1: tamanuid,         ; uuid or string id

    2: ts,               ; created_at
    3: ts,               ; updated_at
    4: ts / null,        ; deleted_at

    5: int,              ; updated_at_sync_tick
    6: tamanuid / null,  ; updated_by_user_id

    ? 23: rowdata,       ; full data from the table row
    ; 23 is the largest int that's encoded in a single byte,
    ; and we're unlikely to ever have 17 more fields anyway.
}
